//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int course_id { get; set; }
        public string course_name { get; set; }
        public string course_type { get; set; }
        public string course_teaching_method { get; set; }
        public string course_level { get; set; }
        public string course_description { get; set; }
        public string course_link { get; set; }
    
        public virtual Course_Provider Course_Provider { get; set; }
    }
}
