//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRSP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class User
    {
        public int user_id { get; set; }

        [Required(ErrorMessage ="Please enter a valid email")]
        [EmailAddress]
        [Display(Name = "Email *")]
        [Remote("IsEmailExists", "Users", HttpMethod = "POST", ErrorMessage = "Email already subscribed")]
        [MaxLength(50, ErrorMessage = "Too long")]
        public string user_email { get; set; }

        [Required(ErrorMessage = "Please enter first name")]
        [Display(Name = "First Name *")]
        [MaxLength(50)]
        public string user_first_name { get; set; }

        [Required(ErrorMessage = "Please enter last name")]
        [Display(Name = "Last Name *")]
        [MaxLength(50)]
        public string user_last_name { get; set; }

        [Display(Name = "Address")]
        [MaxLength(100)]
        public string user_address { get; set; }

        [Display(Name = "Phone Number")]
        [Phone(ErrorMessage = "Please enter a valid phone number")]
        public string user_phone_number { get; set; }
    }
}
